# Задание №1

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29
1. Сложите массивы и возведите элементы получившегося массива в квадрат:

In [2]:
import numpy as np

a = np.arange(1,7) * 2
b = np.array([7, 11, 15, 18, 23, 29])
print((a + b) ** 2)

[  81  225  441  676 1089 1681]


2. Выведите все элементы из первого массива, индексы которых соответствуют индексам тех элементов второго массива, которые больше 12 и дают остаток 3 при деление на 5.

In [3]:
a[np.where ((b > 12) & (b % 5 == 3))]

array([ 8, 10])

3. Проверьте условие "Элементы первого массива делятся на 4, элементы второго массива меньше 14".
(Подсказка: в результате должен получиться массив с True и False)

In [4]:
(a % 4 == 0) & (b < 14)

array([False,  True, False, False, False, False])

# Задание №2

Найдите интересный для вас датасет. Например, можно выбрать датасет тут. http://data.un.org/Explorer.aspx (выбираете датасет, жмете на view data, потом download, выбирайте csv формат)
Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
Проанализируйте и прокомментируйте содержательно получившиеся результаты
Все комментарии оформляйте строго в ячейках формата markdown

In [7]:
import csv
import numpy as np 
with open('Energy data 1990 - 2020.csv', 'r', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    glob = []
    rus = []
    next(reader)
    for i in reader:
        glob.append(float(i[3]))
        rus.append(float(i[4]))
    stat_glob = np.array(glob)
    stat_rus = np.array(rus)
    print(f"Выбросы от сжыгание топливо в мире  {np.mean(stat_glob)}, Выбросы от сжыгание топливо в Росии: {np.mean(stat_rus)}")
    print(f"Среднее коэффициент выбросов в мире {np.std(stat_glob)}, Среднее коэффициент выбросов в России: {np.std(stat_rus)}")
    print(f"Интенсивность при неизменном паритете покупательной спасобности в мире {np.median(stat_glob)}, Интенсивность при неизменном паритете покупательной спасобности в России: {np.var(stat_rus)}")
    print(f"Общее производства эненгии в мире {np.var(stat_glob)}, Общее производства эненгии в России: {np.var(stat_rus)}")
    
    

Выбросы от сжыгание топливо в мире  550.3751784030945, Выбросы от сжыгание топливо в Росии: 2.2385420448174487
Среднее коэффициент выбросов в мире 1212.612848530972, Среднее коэффициент выбросов в России: 0.5603883620707869
Интенсивность при неизменном паритете покупательной спасобности в мире 221.03628085, Интенсивность при неизменном паритете покупательной спасобности в России: 0.3140351163443793
Общее производства эненгии в мире 1470429.9204223985, Общее производства эненгии в России: 0.3140351163443793
